### ISSUE TITLE
指摘事項

### ISSUE THREAD

**Issue by sudahiroshi** [ren51/sotsuron#1]
1章
1段落目の「大学では論文やレポート課題などを書かなければならない大学生に対して，論理的な思考力や論理的文章作成能力の要求が高まっている．」←文章が矛盾しています．
2段落目の冒頭：「しかし」で段落をつなげていますが，おかしいです．
2段落目：「主張や根拠」がここで初めて出てきています．もっと前の方で主張や根拠が必要であることを書きましょう．

2章
「2.2.3 アウトラインの作成する」←日本語がおかしいです．
2.2.3でwordでのアウトライン作成の話を出していますが，この章は論文の書き方という論理的な話をする場所です．wordの話は他に移しましょう．

3章
3.2の箇条書きの後ろの段落の先頭が空いていません．
3.1で「答えのない問題を扱い」とありますが，3.3では「答えのない問題を扱うことが多く」となっています．矛盾しているので統一しましょう．

4章
4章でアウトラインプロセッサなどの例を出していますが，単に紹介してるだけで「こういう場合に良いor悪い」が伝わってきません．
4.2 1回だけ，通常の文字で「LaTeX」となっている箇所があります．
4.4 マインドマップは手法なので，ツールと並べると違和感があります．4章のタイトルに「ソフトウェアや手法の紹介」と書いてあるのは分かりますが，違和感のほうが大きいです．

5章
5.1.3 1行目「使用」→「仕様」
2段落目「これまでも多くのAPIが使用されてきたが〜数多く使われてきた．」←日本語がおかしいです．
3段落目 Canvas, Video, File API, WebWorkerがプラグインのように読めます．
5.3.1 「新しくAPI」→「新しいAPI」
5.4 1行目の文章で書いてあることがおかしくて，PWAの実態が伝わりません．PWAとはこういうものだ！と一文で伝えてください．
5.4 「プッシュ通知の可能」？？？
5.4 「PWAの使用例として図6に示す」←日本語がおかしいです．
5.4 図6の説明をしてください．あと，ホーム画面に設置したスクリーンショットも欲しいです．
5.4 ネイティブアプリとWebアプリを説明してからPWAを説明したほうが良さそうです．

6.1 「アウトラインの作成をにおいて」
6.3 起動した際の最初の画面から説明しましょう．これだといきなり課題名の入力になっていて，唐突に始まった感じがします．

結言　章番号がありません．

**Comment by ren51** [comment]
三浦です。

修正しました。
チェックお願いします。


2020年1月23日(木) 14:19 SUDA Hiroshi <notifications@github.com>:
